#cloud-config
autoinstall:
  storage:
    layout:
      name: lvm
      policy: all
      encryption: luks  # Enables disk encryption
      password: "301097"  # Passphrase for encryption
    swap:
      swap: 4G
    grub:
      reorder_uefi: False
  drivers:
    install: true
  early-commands: []
  late-commands:
    - curtin in-target --target=/target -- wget -O /home/ubuntu/script.sh https://landscape.infobip.com/static/deploy/enroll.sh
    - curtin in-target --target=/target -- bash /home/ubuntu/enroll.sh
  version: 1
