#cloud-config
autoinstall:
  refresh-installer:
    update: true
    channel: latest/stable
  apt:
    disable_components: []
    fallback: abort
    geoip: false
    mirror-selection:
      primary:
        - country-mirror
        - arches: &id001
            - amd64
            - i386
          uri: http://archive.ubuntu.com/ubuntu/
        - arches: &id002
            - s390x
            - arm64
            - armhf
            - powerpc
            - ppc64el
            - riscv64
          uri: http://ports.ubuntu.com/ubuntu-ports
    preserve_sources_list: false
    security:
      - arches: *id001
        uri: http://security.ubuntu.com/ubuntu/
      - arches: *id002
        uri: http://ports.ubuntu.com/ubuntu-ports
  codecs:
    install: true
  drivers:
    install: true
  kernel:
    package: linux-generic-hwe-24.04
  keyboard:
    layout: us
    variant: ''
  locale: en_US.UTF-8
  network:
    version: 2
    ethernets:
      ens33:
        match:
          name: "en*"
        dhcp4: true
      eth1:
        match:
          name: "eth*"
        dhcp4: true
  oem:
    install: auto
  source:
    id: ubuntu-desktop-minimal
  storage:
    layout:
      name: lvm
      sizing-policy: all
      encryption: luks
      password: "301097"
    swap:
      size: 4G
    grub:
      reorder_uefi: False
  identity:
    realname: "Salazar Slytherin"
    hostname: "sslytherin"
    username: "IB-SSLYTHERIN-L"
    password: "$6$jMIpAD1dGkm6sqfJ$HF6uWZp3lbYMjyI3jWUE1j51R9sqCkX8tjrp3xut2AWs3r2Ou9JGyZu1Xr7D3VF3B4X2gYCfjQatKoxAbDGSu0"
  timezone: Europe/Sarajevo
  updates: security
  late-commands:
    - curtin in-target --target=/target -- apt-get update
    - curtin in-target --target=/target -- apt-get install -y wget
    - curtin in-target --target=/target -- mkdir -p /home/sslytherin/scripts
    - curtin in-target --target=/target -- wget -O /home/sslytherin/scripts/setup_user.sh https://github.com/DonBianco/UbuntuAutoInstall/raw/main/setup_user.sh
    - curtin in-target --target=/target -- wget -O /home/sslytherin/scripts/enroll.sh https://github.com/DonBianco/UbuntuAutoInstall/raw/main/enroll.sh
    - curtin in-target --target=/target -- chmod +x /home/sslytherin/scripts/setup_user.sh
    - curtin in-target --target=/target -- chmod +x /home/sslytherin/scripts/enroll.sh
  runcmd:
    - sudo bash /home/sslytherin/scripts/setup_user.sh
    - touch /home/sslytherin/setup_done.flag
  version: 1

# Ensure enroll.sh runs only after reboot if setup_user.sh was completed.
write_files:
  - path: /etc/rc.local
    content: |
      #!/bin/bash
      if [ -f /home/sslytherin/setup_done.flag ]; then
        sudo bash /home/sslytherin/scripts/enroll.sh
        rm -f /home/sslytherin/setup_done.flag
      fi
      exit 0
    permissions: '0755'

