#cloud-config
autoinstall:
  identity:
  hostname: ${user.hostname}  # User will input their own hostname
  username: ${user.username}  # User will input their own username
user-data:
    password: $6$5lpwCLs$2EB3ltav3j/fdeNQtyU91j6lp8HVJ59aWtZHQU2qr.hjm5gha2x9g6eWvS4rVYFWu7Tth40IQfPqW/u10L0Vo0
  network:
    version: 2
    renderer: NetworkManager
  refresh-installer:
    update: no
  keyboard:
    layout: gb
  locale: en_GB.UTF-8
  storage:
    layout:
      name: lvm
      policy: all
      encryption: luks  # Enables disk encryption
      password: "301097"  # Passphrase for encryption
    swap:
      swap: 4G
    grub:
      reorder_uefi: False
  drivers:
    install: true
  early-commands: []
  late-commands:
    - curtin in-target --target=/target -- wget -O /home/ubuntu/script.sh https://landscape.infobip.com/static/deploy/enroll.sh
    - curtin in-target --target=/target -- bash /home/ubuntu/enroll.sh
  version: 1
