#cloud-config
autoinstall:
  version: 1
  identity:
    username: sslytherin
    hostname: IB-SSLYTHERIN-L
    password: '$6$rounds=4096$4N/8F013fjJKEsZ.$yxG5RGuIMGqYbMQQcmGUPbtBAGkwVBZD6ptVwTdjv8yt4JsJCIdTrsbH4PU4QIQgbyMBBDg6vqLohYXs.erQT/'

  storage:
    layout:
      name: lvm
      policy: all
      encryption: luks
      password: "301097"
    swap:
      size: 16G
    grub:
      reorder_uefi: False

  early-commands: []

  late-commands:
    - curtin in-target --target=/target -- apt-get update
    - curtin in-target --target=/target -- apt-get install -y wget
    - curtin in-target --target=/target -- mkdir -p /home/sslytherin
    - curtin in-target --target=/target -- wget -O /home/sslytherin/enroll.sh https://landscape.infobip.com/static/deploy/enroll.sh
    - curtin in-target --target=/target -- chmod +x /home/sslytherin/enroll.sh

  runcmd:
    - curtin in-target --target=/target -- apt-get update
    - curtin in-target --target=/target -- apt-get upgrade -y
    - curtin in-target --target=/target -- apt-get install -y linux-firmware
    - curtin in-target --target=/target -- bash /home/sslytherin/enroll.sh
